#!/usr/bin/env node

import fs from 'node:fs';
import util from 'node:util';

const { positionals } = util.parseArgs({allowPositionals: true});

for (let filepath of positionals) {
    let sql = fs.readFileSync(filepath, 'utf-8');
    sql = sql.replace(/CREATE DATABASE IF NOT EXISTS restodb;\n/g, "");
    sql = sql.replace(/\s+AUTO_INCREMENT\s+=\s\d+/g, "");
    sql = sql.replace(/(\w+)\s+AUTO_INCREMENT/g, "$1 GENERATED BY DEFAULT AS IDENTITY(START WITH 1000)");
    sql = sql.replace(/(\w+)\s+(DATETIME|DATE|TIME)/g, "$1 TIMESTAMP");
    sql = sql.replace(/ON\s+UPDATE\s+CURRENT_TIMESTAMP/g, "");
    sql = sql.replace(/DELIMITER.*\n/g, "");
    sql = sql.replace(/(\s)((?:OLD|NEW)\.)/g, "$1:$2");

    console.info('WHENEVER OSERROR EXIT FAILURE ROLLBACK');
    console.info('WHENEVER SQLERROR EXIT FAILURE ROLLBACK');
    console.info(sql);
    console.info('EXIT;');

}

